apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix

spec:
   replicas: 3
   selector:
      matchLabels:
          app: netflix

   template:
        metadata:
            app: netflix
        spec:
            containers:
                  - name: netflix
                    image: shubhamm18/netflix-clone:latest
                    port:
                      - containerPort: 3000
                    imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata: 
    name: nteflix-service

spec:
  type: ClusterIP
  selector:
      app: netflix
  ports:
   - port: 3000
     targetPort: 3000

        
