apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: luminary
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: shubhamm18/luminary:backend
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              valueFrom:
                  configMapKeyRef:
                      name: luminary-config
                      key:  DB_HOST
            - name: DB_NAME
              valueFrom:
                  configMapKeyRef:
                      name: luminary-config
                      key:  DB_NAME
            - name: DB_USER
              valueFrom:
                  configMapKeyRef:
                      name: luminary-config
                      key:  DB_USER
            - name: DB_PASSWORD
              valueFrom:
                  secretKeyRef:
                      name: luminary-secret
                      key:  DB_PASSWORD
            - name: MYSQL_PORT
              valueFrom:
                  configMapKeyRef:
                      name: luminary-config
                      key:  MYSQL_PORT
            - name: JWT_SECRET
              valueFrom:
                  secretKeyRef:
                      name: luminary-secret
                      key:  JWT_SECRET
            - name: AGORA_APP_ID
              valueFrom:
                  secretKeyRef:
                      name: luminary-secret
                      key:  AGORA_APP_ID
            - name: AGORA_APP_CERTIFICATE
              valueFrom:
                  secretKeyRef:
                      name: luminary-secret
                      key:  AGORA_APP_CERTIFICATE
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: luminary
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30080
