apiVersion: v1
kind: ConfigMap
metadata:
  name: luminary-config
  namespace: luminary

data:

   DB_HOST: mysql-service
   DB_NAME: project_management_db
   MYSQL_DATABASE: project_management_db
   MYSQL_ROOT_USER: root
   DB_USER: root
   MYSQL_PORT: "3306"
